import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Home': 'Home',
          'Categories': 'Categories',
          'Search': 'Search',
          'Settings': 'Settings',
          'Login failed': 'Login failed',
          'Login success': 'Login success',
          'Account': 'Account',
          'Password': 'Password',
          'Login': 'Login',
          'Login to your Pica Account': 'Login to your Pica Account',
          "Failed to login": "Failed to login",
          "Failed to get token": "Failed to get token",
          "Login expired and re-login failed":
              "Login expired and re-login failed",
          "Connection Timeout": "Connection Timeout",
          "Unknown Error": "Unknown Error",
          "Please enter account and password":
              "Please enter account and password",
          "Incorrect account or password": "Incorrect account or password",
          "Connection Failed. Please check your network":
              "Connection Failed. Please check your network",
          'Appearance': 'Appearance',
          'Color Theme': 'Color Theme',
          "zinc": "Zinc",
          "slate": "Slate",
          "red": "Red",
          "rose": "Rose",
          "orange": "Orange",
          "green": "Green",
          "blue": "Blue",
          "yellow": "Yellow",
          "violet": "Violet",
          'Select an item': 'Select an item',
          'Dark Mode': 'Dark Mode',
          'Follow System': 'Follow System',
          'Light': 'Light',
          'Dark': 'Dark',
          "Me": "Me",
          "Picacg": "Picacg",
          "Set stream": "Set stream",
          "Stream 1": "Stream 1",
          "Stream 2": "Stream 2",
          "Stream 3": "Stream 3",
          "Stream 4": "Stream 4",
          "Gallery domain": "Gallery domain",
          "Set image quality": "Set image quality",
          "Low": "Low",
          "Medium": "Medium",
          "High": "High",
          "Original image": "Original image",
          "Set search and category sorting mode":
              "Set search and category sorting mode",
          "Auto check-in": "Auto check-in",
          "Comic list display mode": "Comic list display mode",
          "Check-in successful": "Check-in successful",
          "Manga sources": "Manga sources",
          "New to Old": "New to Old",
          "Old to New": "Old to New",
          "Most Likes": "Most Likes",
          "Most Viewed": "Most Viewed",
          "Language": "Language",
          "Network Error": "Network Error",
          "Load Bookmarks Failed": "Load Bookmarks Failed",
          "Failed to load data": "Failed to load data",
          'Page Number': 'Page Number',
          'Invalid Page Number': 'Invalid Page Number',
          "Cancel": "Cancel",
          "Ok": "Ok",
          "Prev Page": "Prev Page",
          "Next Page": "Next Page",
          'Jump to Page': 'Jump to Page',
//below are translation with parameters
          "at_page": "Page @page/@total",
        },
        'zh_CN': {
          'Home': '首页',
          'Categories': '分类',
          'Search': '搜索',
          'Settings': '设置',
          'Login failed': '登录失败',
          'Login success': '登录成功',
          'Account': '账号',
          'Password': '密码',
          'Login': '登录',
          'Login to your Pica Account': '登录到您的Pica帐户',
          'Failed to login': '登录失败',
          'Failed to get token': '获取token失败',
          'Login expired and re-login failed': "登录失效且重新登录失败",
          "Connection Timeout": "连接超时",
          "Unknown Error": "未知错误",
          "Please enter account and password": "请输入账号和密码",
          "Incorrect account or password": "账号或密码错误",
          "Connection Failed. Please check your network": "连接失败，请检查您的网络",
          'Appearance': '外观',
          'Color Theme': '颜色主题',
          "zinc": "黑/白",
          "slate": "灰",
          "red": "红",
          "rose": "玫瑰",
          "orange": "橙",
          "green": "绿",
          "blue": "蓝",
          "yellow": "黄",
          "violet": "紫",
          'Select an item': '至少选择一个',
          'Dark Mode': '深色模式',
          'Follow System': '跟随系统',
          'Light': '浅色',
          'Dark': '深色',
          "Me": "我",
          "Picacg": "哔咔漫画",
          "Set stream": "设置分流",
          "Stream 1": "分流1",
          "Stream 2": "分流2",
          "Stream 3": "分流3",
          "Stream 4": "分流4",
          "Gallery domain": "画廊站点",
          "Set image quality": "设置图片质量",
          "Low": "低",
          "Medium": "中",
          "High": "高",
          "Original image": "原图",
          "Set search and category sorting mode": "设置搜索和分类排序模式",
          "Auto check-in": "自动签到",
          "Comic list display mode": "漫画列表显示模式",
          "Check-in successful": "签到成功",
          "Manga sources": "漫画源",
          "New to Old": "新到旧",
          "Old to New": "旧到新",
          "Most Likes": "最受欢迎",
          "Most Viewed": "最多查看",
          "Language": "语言",
          "Network Error": "网络错误",
          "Load Bookmarks Failed": "获取收藏夹失败",
          "Failed to load data": "获取数据失败",
          'Page Number': '页码',
          'Invalid Page Number': '无效的页码',
          "Cancel": "取消",
          "Ok": "确定",
          "Prev Page": "上一页",
          "Next Page": "下一页",
          'Jump to Page': '跳转到页',
//below are translation with parameters
          "at_page": "第@page/@total页",
        },
        'zh_TW': {
          'Home': '首頁',
          'Categories': '分類',
          'Search': '搜索',
          'Settings': '設置',
          'Login failed': '登錄失敗',
          'Login success': '登錄成功',
          'Account': '賬號',
          'Password': '密碼',
          'Login': '登錄',
          'Login to your Pica Account': '登錄到您的Pica帳戶',
          'Failed to login': '登錄失敗',
          'Failed to get token': '獲取token失敗',
          'Login expired and re-login failed': "登錄失效且重新登錄失敗",
          "Connection Timeout": "連接超時",
          "Unknown Error": "未知錯誤",
          "Please enter account and password": "請輸入賬號和密碼",
          "Incorrect account or password": "賬號或密碼錯誤",
          "Connection Failed. Please check your network": "連接失敗，請檢查您的網絡",
          'Appearance': '外觀',
          'Color Theme': '顏色主題',
          "zinc": "黑/白",
          "slate": "灰",
          "red": "紅",
          "rose": "玫瑰",
          "orange": "橙",
          "green": "綠",
          "blue": "藍",
          "yellow": "黃",
          "violet": "紫",
          'Select an item': '至少選擇一個',
          'Dark Mode': '深色模式',
          'Follow System': '跟隨系統',
          'Light': '淺色',
          'Dark': '深色',
          "Me": "我",
          "Picacg": "哔咔漫畫",
          "Set stream": "設置分流",
          "Stream 1": "分流1",
          "Stream 2": "分流2",
          "Stream 3": "分流3",
          "Stream 4": "分流4",
          "Gallery domain": "畫廊站點",
          "Set image quality": "設置圖片質量",
          "Low": "低",
          "Medium": "中",
          "High": "高",
          "Original image": "原圖",
          "Set search and category sorting mode": "設置搜索和分類排序模式",
          "Auto check-in": "自動簽到",
          "Comic list display mode": "漫畫列表顯示模式",
          "Check-in successful": "簽到成功",
          "Manga sources": "漫畫源",
          "New to Old": "新到舊",
          "Old to New": "舊到新",
          "Most Likes": "最受歡迎",
          "Most Viewed": "最多查看",
          "Language": "語言",
          "Network Error": "網絡錯誤",
          "Load Bookmarks Failed": "獲取收藏夾失敗",
          "Failed to load data": "獲取數據失敗",
          'Page Number': '頁碼',
          'Invalid Page Number': '無效的頁碼',
          "Cancel": "取消",
          "Ok": "確定",
          "Prev Page": "上一頁",
          "Next Page": "下一頁",
          'Jump to Page': '跳轉到頁',
//below are translation with parameters
          "at_page": "第@page/@total頁",
        },
      };
}
