import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Home': 'Home',
          'Categories': 'Categories',
          'Search': 'Search',
          'Settings': 'Settings',
          'Login failed': 'Login failed',
          'Login success': 'Login success',
          'Account': 'Account',
          'Password': 'Password',
          'Login': 'Login',
          'Login to your Pica Account': 'Login to your Pica Account',
          "Failed to login": "Failed to login",
          "Failed to get token": "Failed to get token",
          "Login expired and re-login failed":
              "Login expired and re-login failed",
          "Connection Timeout": "Connection Timeout",
          "Unknown Error": "Unknown Error",
          "Please enter account and password":
              "Please enter account and password",
          "Incorrect account or password": "Incorrect account or password",
          "Connection Failed. Please check your network":
              "Connection Failed. Please check your network",
          'Appearance': 'Appearance',
          'Color Theme': 'Color Theme',
          "zinc": "Zinc",
          "slate": "Slate",
          "red": "Red",
          "rose": "Rose",
          "orange": "Orange",
          "green": "Green",
          "blue": "Blue",
          "yellow": "Yellow",
          "violet": "Violet",
          'Select an item': 'Select an item',
          'Dark Mode': 'Dark Mode',
          'Follow System': 'Follow System',
          'Light': 'Light',
          'Dark': 'Dark',
          "Me": "Me",
        },
        'zh_CN': {
          'Home': '首页',
          'Categories': '分类',
          'Search': '搜索',
          'Settings': '设置',
          'Login failed': '登录失败',
          'Login success': '登录成功',
          'Account': '账号',
          'Password': '密码',
          'Login': '登录',
          'Login to your Pica Account': '登录到您的Pica帐户',
          'Failed to login': '登录失败',
          'Failed to get token': '获取token失败',
          'Login expired and re-login failed': "登录失效且重新登录失败",
          "Connection Timeout": "连接超时",
          "Unknown Error": "未知错误",
          "Please enter account and password": "请输入账号和密码",
          "Incorrect account or password": "账号或密码错误",
          "Connection Failed. Please check your network": "连接失败，请检查您的网络",
          'Appearance': '外观',
          'Color Theme': '颜色主题',
          "zinc": "黑/白",
          "slate": "灰",
          "red": "红",
          "rose": "玫瑰",
          "orange": "橙",
          "green": "绿",
          "blue": "蓝",
          "yellow": "黄",
          "violet": "紫",
          'Select an item': '至少选择一个',
          'Dark Mode': '深色模式',
          'Follow System': '跟随系统',
          'Light': '浅色',
          'Dark': '深色',
          "Me": "我",
        },
        'zh_TW': {
          'Home': '首頁',
          'Categories': '分類',
          'Search': '搜索',
          'Settings': '設置',
          'Login failed': '登錄失敗',
          'Login success': '登錄成功',
          'Account': '賬號',
          'Password': '密碼',
          'Login': '登錄',
          'Login to your Pica Account': '登錄到您的Pica帳戶',
          'Failed to login': '登錄失敗',
          'Failed to get token': '獲取token失敗',
          'Login expired and re-login failed': "登錄失效且重新登錄失敗",
          "Connection Timeout": "連接超時",
          "Unknown Error": "未知錯誤",
          "Please enter account and password": "請輸入賬號和密碼",
          "Incorrect account or password": "賬號或密碼錯誤",
          "Connection Failed. Please check your network": "連接失敗，請檢查您的網絡",
          'Appearance': '外觀',
          'Color Theme': '顏色主題',
          "zinc": "黑/白",
          "slate": "灰",
          "red": "紅",
          "rose": "玫瑰",
          "orange": "橙",
          "green": "綠",
          "blue": "藍",
          "yellow": "黃",
          "violet": "紫",
          'Select an item': '至少選擇一個',
          'Dark Mode': '深色模式',
          'Follow System': '跟隨系統',
          'Light': '淺色',
          'Dark': '深色',
          "Me": "我",
        },
      };
}
