import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Home': 'Home',
          'Categories': 'Categories',
          'Search': 'Search',
          'Settings': 'Settings',
          'Login failed': 'Login failed',
          'Login success': 'Login success',
          'Account': 'Account',
          'Password': 'Password',
          'Login': 'Login',
          'Login to your Pica Account': 'Login to your Pica Account',
          "Failed to login": "Failed to login",
          "Failed to get token": "Failed to get token",
          "Login expired and re-login failed":
              "Login expired and re-login failed",
          "Connection Timeout": "Connection Timeout",
          "Unknown Error": "Unknown Error",
          "Please enter account and password":
              "Please enter account and password",
          "Incorrect account or password": "Incorrect account or password",
          "Connection Failed. Please check your network":
              "Connection Failed. Please check your network",
          'Appearance': 'Appearance',
          'Color Theme': 'Color Theme',
          "zinc": "Zinc",
          "slate": "Slate",
          "red": "Red",
          "rose": "Rose",
          "orange": "Orange",
          "green": "Green",
          "blue": "Blue",
          "yellow": "Yellow",
          "violet": "Violet",
          'Select an item': 'Select an item',
          'Dark Mode': 'Dark Mode',
          'Follow System': 'Follow System',
          'Light': 'Light',
          'Dark': 'Dark',
          "Me": "Me",
          "Picacg": "Picacg",
          "Set stream": "Set stream",
          "Stream 1": "Stream 1",
          "Stream 2": "Stream 2",
          "Stream 3": "Stream 3",
          "Stream 4": "Stream 4",
          "Gallery domain": "Gallery domain",
          "Set image quality": "Set image quality",
          "Low": "Low",
          "Medium": "Medium",
          "High": "High",
          "Original image": "Original image",
          "Set search and category sorting mode":
              "Set search and category sorting mode",
          "Auto check-in": "Auto check-in",
          "Comic list display mode": "Comic list display mode",
          "Check-in successful": "Check-in successful",
          "Manga sources": "Manga sources",
          "New to Old": "New to Old",
          "Old to New": "Old to New",
          "Most Likes": "Most Likes",
          "Most Viewed": "Most Viewed",
          "Language": "Language",
          "Network Error": "Network Error",
          "Load Bookmarks Failed": "Load Bookmarks Failed",
          "Failed to load data": "Failed to load data",
          'Page Number': 'Page Number',
          'Invalid Page Number': 'Invalid Page Number',
          "Cancel": "Cancel",
          "Ok": "Ok",
          "Prev Page": "Prev Page",
          "Next Page": "Next Page",
          'Jump to Page': 'Jump to Page',
          'Manga Settings': 'Manga Settings',
          "Preload number of pages": "Preload number of pages",
          "Preload when enter details page": "Preload when enter details page",
          "Finished": "Finished",
          "Category": "Category",
          "Tags": "Tags",
          "Description: ": "Description: ",
          "Updated": "Updated",
          "All Comments": "All Comments",
          "Episodes": "Episodes",
          "Comments": "Comments",
          "Related": "Related",
          "Search History": "Search History",
          "Clean history?": "Clean history?",
          "Clear search history": "Clear search history",
          "No Comments": "No Comments",
          "No Related": "No Related",
          "Home Page": "Home Page",
          "Left": "Left",
          "Middle": "Middle",
          "Right": "Right",
          "Load More": "Load More",
          "Failed to reply": "Failed to reply",
          "Internal Error": "Internal Error",
          "Permission denied": "Permission denied",
          "Saved": "Saved",
          "Block keyword": "Block keyword",
          "Blocked keyword": "Blocked keyword",
          "Orientation": "Orientation",
          "Auto next page": "Auto next page",
          "Save": "Save",
          "Share": "Share",
          "Pages": "Pages",
          "Page": "Page",
          "Back": "Back",
          "Read Settings": "Read Settings",
          "Read Mode": "Read Mode",
          "Left to Right": "Left to Right",
          "Right to Left": "Right to Left",
          "Top to Bottom": "Top to Bottom",
          "Top to Bottom(Scroll view)": "Top to Bottom(Scroll view)",
          "Duo Page": "Duo Page",
          "Duo Page(reversed)": "Duo Page(reversed)",
          "Auto Page Turning Interval": "Auto Page Turning Interval",
          "Animation Duration": "Animation Duration",
          "Image Layout": "Image Layout",
          "Contained": "Contained",
          "Covered": "Covered",
          "Limit Image Width": "Limit Image Width",
          "Enabled": "Enabled",
          "Disabled": "Disabled",
          "Tap to Next Page Threshold": "Tap to Next Page Threshold",
          "Dark Background": "Dark Background",
          "Blocked Keywords": "Blocked Keywords",
          "Add Blocked Keywords": "Add Blocked Keywords",
          "Remove Blocked Keywords": "Remove Blocked Keywords",
          "Empty": "Empty",
          "Blocked Categories": "Blocked Categories",
          "Also applies to all filters": "Also applies to all filters",
          "Set page view mode": "Set page view mode",
          "Page View": "Page View",
          "Infinite Scroll": "Infinite Scroll",
          "Leaderboard": "Leaderboard",
          "Random": "Random",
          "Latest": "Latest",
          "Add Tag": "Add Tag",
          "Main Page Categories/Tags": "Main Page Categories/Tags",
          "Set what to show on main page": "Set what to show on main page",
          "Display on Main Page": "Display on Main Page",
          "Main Page": "Main Page",
          "Search Page": "Search Page",
          "Me Page": "Me Page",
          "Close": "Close",
          "Bookmarks": "Bookmarks",
          "Manage": "Manage",
          'Main orientation': 'Main orientation',
          'Auto': 'Auto',
          'Portrait': 'Portrait',
          'Landscape': 'Landscape',
          "My Bookmarks": "My Bookmarks",
          "Failed to update slogan": "Failed to update slogan",
          "Slogan can't be empty": "Slogan can't be empty",
          "My History": "My History",
          'Clear History': 'Clear History',
          'Clear': 'Clear',
          'Clear all history?': 'Clear all history?',
          "New password is the same as the old password":
              "New password is the same as the old password",
          "Failed to update password": "Failed to update password",
          "Password updated": "Password updated",
          "Change Password": "Change Password",
          "Logout": "Logout",
          "Change": "Change",
          "Old Password": "Old Password",
          "New Password": "New Password",
          "Confirm Password": "Confirm Password",
          "Slogan": "Slogan",
          "Old password is incorrect": "Old password is incorrect",
          'Not Logged In': 'Not Logged In',
          "Last Read:": "Last Read:",
          'Cache & Restore': 'Cache & Restore',
          'Clear Cache Period': 'Clear Cache Period',
          "Day": "Day",
          "Days": "Days",
          'Clear Cache': 'Clear Cache',
          'Are you sure to clear cache?': 'Are you sure to clear cache?',
          'Restore': 'Restore',
          "Cache Cleared": "Cache Cleared",
          "General Settings": "General Settings",
          "Initialize App": "Initialize App",
          "Are you sure to initialize app?": "Are you sure to initialize app?",
          "App Initialized": "App Initialized",
          "H24": "24h",
          "D7": "7d",
          "D30": "30d",
          "The purpose of this App is only for learning, communication, and personal interest. Any content displayed comes from the internet and is not related to the developer":
              "The purpose of this App is only for learning, communication, and personal interest. Any content displayed comes from the internet and is not related to the developer",
          "If you encounter any problems during use, please first confirm whether it is a problem with your device, and then provide feedback":
              "If you encounter any problems during use, please first confirm whether it is a problem with your device, and then provide feedback",
          "The developer is not responsible for whether the problem can be solved":
              "The developer is not responsible for whether the problem can be solved",
//below are translation with parameters
          "at_page": "Page @page/@total",
          "block_cate": "Block Category @cate?",
          "continue_page": "Continue:@eps-P@page",
        },
        'zh_CN': {
          'Home': '首页',
          'Categories': '分类',
          'Search': '搜索',
          'Settings': '设置',
          'Login failed': '登录失败',
          'Login success': '登录成功',
          'Account': '账号',
          'Password': '密码',
          'Login': '登录',
          'Login to your Pica Account': '登录到您的Pica帐户',
          'Failed to login': '登录失败',
          'Failed to get token': '获取token失败',
          'Login expired and re-login failed': "登录失效且重新登录失败",
          "Connection Timeout": "连接超时",
          "Unknown Error": "未知错误",
          "Please enter account and password": "请输入账号和密码",
          "Incorrect account or password": "账号或密码错误",
          "Connection Failed. Please check your network": "连接失败，请检查您的网络",
          'Appearance': '外观',
          'Color Theme': '颜色主题',
          "zinc": "黑/白",
          "slate": "灰",
          "red": "红",
          "rose": "玫瑰",
          "orange": "橙",
          "green": "绿",
          "blue": "蓝",
          "yellow": "黄",
          "violet": "紫",
          'Select an item': '至少选择一个',
          'Dark Mode': '深色模式',
          'Follow System': '跟随系统',
          'Light': '浅色',
          'Dark': '深色',
          "Me": "我的",
          "Picacg": "哔咔漫画",
          "Set stream": "设置分流",
          "Stream 1": "分流1",
          "Stream 2": "分流2",
          "Stream 3": "分流3",
          "Stream 4": "分流4",
          "Gallery domain": "画廊站点",
          "Set image quality": "设置图片质量",
          "Low": "低",
          "Medium": "中",
          "High": "高",
          "Original image": "原图",
          "Set search and category sorting mode": "设置搜索和分类排序模式",
          "Auto check-in": "自动签到",
          "Comic list display mode": "漫画列表显示模式",
          "Check-in successful": "签到成功",
          "Manga sources": "漫画源",
          "New to Old": "新到旧",
          "Old to New": "旧到新",
          "Most Likes": "最受欢迎",
          "Most Viewed": "最多查看",
          "Language": "语言",
          "Network Error": "网络错误",
          "Load Bookmarks Failed": "获取收藏夹失败",
          "Failed to load data": "获取数据失败",
          'Page Number': '页码',
          'Invalid Page Number': '无效的页码',
          "Cancel": "取消",
          "Ok": "确定",
          "Prev Page": "上一页",
          "Next Page": "下一页",
          'Jump to Page': '跳转到页',
          'Manga Settings': '漫画设置',
          "Preload number of pages": "预加载页数",
          "Preload when enter details page": "进入详情页时预加载",
          "Finished": "完结",
          "Category": "分类",
          "Tags": "标签",
          "Description: ": "简介: ",
          "Updated": "更新",
          "All Comments": "全部评论",
          "Episodes": "章节",
          "Comments": "评论",
          "Related": "相关",
          "Search History": "搜索历史",
          "Clean history?": "清除历史?",
          "Clear search history": "清除搜索历史",
          "No Comments": "暂无评论",
          "No Related": "暂无相关",
          "Home Page": "首页",
          "Left": "左",
          "Middle": "中",
          "Right": "右",
          "Load More": "加载更多",
          "Failed to reply": "回复失败",
          "Internal Error": "内部错误",
          "Permission denied": "权限不足",
          "Saved": "已保存",
          "Block keyword": "屏蔽关键词",
          "Blocked keyword": "已屏蔽关键词",
          "Orientation": "方向",
          "Auto next page": "自动下一页",
          "Save": "保存",
          "Share": "分享",
          "Pages": "页数",
          "Page": "页",
          "Back": "返回",
          "Read Settings": "阅读设置",
          "Read Mode": "阅读模式",
          "Left to Right": "从左到右",
          "Right to Left": "从右到左",
          "Top to Bottom": "从上到下",
          "Top to Bottom(Scroll view)": "从上到下(滚动视图)",
          "Duo Page": "双页",
          "Duo Page(reversed)": "双页(反向)",
          "Auto Page Turning Interval": "自动翻页间隔",
          "Animation Duration": "动画持续时间",
          "Image Layout": "图片布局",
          "Contained": "包含",
          "Covered": "覆盖",
          "Limit Image Width": "限制图片宽度",
          "Enabled": "启用",
          "Disabled": "禁用",
          "Tap to Next Page Threshold": "点击下一页阈值",
          "Dark Background": "深色背景",
          "Blocked Keywords": "屏蔽关键词",
          "Add Blocked Keywords": "添加屏蔽关键词",
          "Remove Blocked Keywords": "移除屏蔽关键词",
          "Empty": "空",
          "Blocked Categories": "屏蔽分类",
          "Also applies to all filters": "同时应用于所有搜索",
          "Set page view mode": "设置页面查看模式",
          "Page View": "分页",
          "Infinite Scroll": "无限滚动",
          "Leaderboard": "排行榜",
          "Random": "随机",
          "Latest": "最新",
          "Add Tag": "添加标签",
          "Main Page Categories/Tags": "主页分类/标签",
          "Set what to show on main page": "设置主页显示内容",
          "Display on Main Page": "主页显示",
          "Main Page": "主页",
          "Search Page": "搜索",
          "Me Page": "我的",
          "Close": "关闭",
          "Bookmarks": "收藏夹",
          "Manage": "管理",
          'Main orientation': '屏幕方向',
          'Auto': '自动',
          'Portrait': '竖屏',
          'Landscape': '横屏',
          "My Bookmarks": "我的收藏",
          "Failed to update slogan": "更新签名失败",
          "Slogan can't be empty": "签名不能为空",
          "My History": "浏览历史",
          "Clear History": "清除历史",
          "Clear": "清除",
          "Clear all history?": "清除所有历史?",
          "New password is the same as the old password": "新密码与旧密码相同",
          "Failed to update password": "更新密码失败",
          "Password updated": "密码已更新",
          "Change Password": "修改密码",
          "Logout": "登出",
          "Change": "修改",
          "Old Password": "旧密码",
          "New Password": "新密码",
          "Confirm Password": "确认密码",
          "Slogan": "签名",
          "Old password is incorrect": "旧密码不正确",
          'Not Logged In': '未登录',
          "Last Read:": "最后阅读:",
          "Cache & Restore": "缓存与恢复",
          "Clear Cache Period": "清除缓存周期",
          "Day": "天",
          "Days": "天",
          "Clear Cache": "清除缓存",
          "Are you sure to clear cache?": "您确定要清除缓存吗？",
          "Restore": "恢复",
          "Cache Cleared": "缓存已清除",
          "General Settings": "常规设置",
          "Initialize App": "初始化应用",
          "Are you sure to initialize app?": "您确定要初始化应用吗？",
          "App Initialized": "应用已初始化",
          "H24": "24h",
          "D7": "7天",
          "D30": "30天",
          "The purpose of this App is only for learning, communication, and personal interest. Any content displayed comes from the internet and is not related to the developer":
              "本App的开发目的仅为学习交流与个人兴趣, 显示的任何内容均来自网络, 与开发者无关",
          "If you encounter any problems during use, please first confirm whether it is a problem with your device, and then provide feedback":
              "如果在使用中发现问题, 请先确认是否为自己的设备问题, 然后再进行反馈",
          "The developer is not responsible for whether the problem can be solved":
              "开发者不对能否解决问题负责",
//below are translation with parameters
          "at_page": "第@page/@total页",
          "block_cate": '屏蔽分类"@cate?"',
          "continue_page": "继续阅读:@eps-P@page",
        },
        'zh_TW': {
          'Home': '首頁',
          'Categories': '分類',
          'Search': '搜索',
          'Settings': '設置',
          'Login failed': '登錄失敗',
          'Login success': '登錄成功',
          'Account': '賬號',
          'Password': '密碼',
          'Login': '登錄',
          'Login to your Pica Account': '登錄到您的Pica帳戶',
          'Failed to login': '登錄失敗',
          'Failed to get token': '獲取token失敗',
          'Login expired and re-login failed': "登錄失效且重新登錄失敗",
          "Connection Timeout": "連接超時",
          "Unknown Error": "未知錯誤",
          "Please enter account and password": "請輸入賬號和密碼",
          "Incorrect account or password": "賬號或密碼錯誤",
          "Connection Failed. Please check your network": "連接失敗，請檢查您的網絡",
          'Appearance': '外觀',
          'Color Theme': '顏色主題',
          "zinc": "黑/白",
          "slate": "灰",
          "red": "紅",
          "rose": "玫瑰",
          "orange": "橙",
          "green": "綠",
          "blue": "藍",
          "yellow": "黃",
          "violet": "紫",
          'Select an item': '至少選擇一個',
          'Dark Mode': '深色模式',
          'Follow System': '跟隨系統',
          'Light': '淺色',
          'Dark': '深色',
          "Me": "我的",
          "Picacg": "哔咔漫畫",
          "Set stream": "設置分流",
          "Stream 1": "分流1",
          "Stream 2": "分流2",
          "Stream 3": "分流3",
          "Stream 4": "分流4",
          "Gallery domain": "畫廊站點",
          "Set image quality": "設置圖片質量",
          "Low": "低",
          "Medium": "中",
          "High": "高",
          "Original image": "原圖",
          "Set search and category sorting mode": "設置搜索和分類排序模式",
          "Auto check-in": "自動簽到",
          "Comic list display mode": "漫畫列表顯示模式",
          "Check-in successful": "簽到成功",
          "Manga sources": "漫畫源",
          "New to Old": "新到舊",
          "Old to New": "舊到新",
          "Most Likes": "最受歡迎",
          "Most Viewed": "最多查看",
          "Language": "語言",
          "Network Error": "網絡錯誤",
          "Load Bookmarks Failed": "獲取收藏夾失敗",
          "Failed to load data": "獲取數據失敗",
          'Page Number': '頁碼',
          'Invalid Page Number': '無效的頁碼',
          "Cancel": "取消",
          "Ok": "確定",
          "Prev Page": "上一頁",
          "Next Page": "下一頁",
          'Jump to Page': '跳轉到頁',
          'Manga Settings': '漫畫設置',
          "Preload number of pages": "預加載頁數",
          "Preload when enter details page": "進入詳情頁時預加載",
          "Finished": "完結",
          "Category": "分類",
          "Tags": "標籤",
          "Description: ": "簡介: ",
          "Updated": "更新",
          "All Comments": "全部評論",
          "Episodes": "章節",
          "Comments": "評論",
          "Related": "相關",
          "Search History": "搜索歷史",
          "Clean history?": "清除歷史?",
          "Clear search history": "清除搜索歷史",
          "No Comments": "暫無評論",
          "No Related": "暫無相關",
          "Home Page": "首頁",
          "Left": "左",
          "Middle": "中",
          "Right": "右",
          "Load More": "加載更多",
          "Failed to reply": "回復失敗",
          "Internal Error": "內部錯誤",
          "Permission denied": "權限不足",
          "Saved": "已保存",
          "Block keyword": "屏蔽關鍵詞",
          "Blocked keyword": "已屏蔽關鍵詞",
          "Orientation": "方向",
          "Auto next page": "自動下一頁",
          "Save": "保存",
          "Share": "分享",
          "Pages": "頁數",
          "Page": "頁",
          "Back": "返回",
          "Read Settings": "閱讀設置",
          "Read Mode": "閱讀模式",
          "Left to Right": "從左到右",
          "Right to Left": "從右到左",
          "Top to Bottom": "從上到下",
          "Top to Bottom(Scroll view)": "從上到下(滾動視圖)",
          "Duo Page": "雙頁",
          "Duo Page(reversed)": "雙頁(反向)",
          "Auto Page Turning Interval": "自動翻頁間隔",
          "Animation Duration": "動畫持續時間",
          "Image Layout": "圖片佈局",
          "Contained": "包含",
          "Covered": "覆蓋",
          "Limit Image Width": "限制圖片寬度",
          "Enabled": "啟用",
          "Disabled": "禁用",
          "Tap to Next Page Threshold": "點擊下一頁閾值",
          "Dark Background": "深色背景",
          "Blocked Keywords": "屏蔽關鍵詞",
          "Add Blocked Keywords": "添加屏蔽關鍵詞",
          "Remove Blocked Keywords": "移除屏蔽關鍵詞",
          "Empty": "空",
          "Blocked Categories": "屏蔽分類",
          "Also applies to all filters": "同時應用於所有搜索",
          "Set page view mode": "設置頁面查看模式",
          "Page View": "分頁",
          "Infinite Scroll": "無限滾動",
          "Leaderboard": "排行榜",
          "Random": "隨機",
          "Latest": "最新",
          "Add Tag": "添加標籤",
          "Main Page Categories/Tags": "主頁分類/標籤",
          "Set what to show on main page": "設置主頁顯示內容",
          "Display on Main Page": "主頁顯示",
          "Main Page": "主頁",
          "Search Page": "搜索",
          "Me Page": "我的",
          "Close": "關閉",
          "Bookmarks": "收藏夾",
          "Manage": "管理",
          'Main orientation': '屏幕方向',
          'Auto': '自動',
          'Portrait': '豎屏',
          'Landscape': '橫屏',
          "My Bookmarks": "我的收藏",
          "Failed to update slogan": "更新簽名失敗",
          "Slogan can't be empty": "簽名不能為空",
          "My History": "瀏覽歷史",
          "Clear History": "清除歷史",
          "Clear": "清除",
          "Clear all history?": "清除所有歷史?",
          "New password is the same as the old password": "新密碼與舊密碼相同",
          "Failed to update password": "更新密碼失敗",
          "Password updated": "密碼已更新",
          "Change Password": "修改密碼",
          "Logout": "登出",
          "Change": "修改",
          "Old Password": "舊密碼",
          "New Password": "新密碼",
          "Confirm Password": "確認密碼",
          "Slogan": "簽名",
          "Old password is incorrect": "舊密碼不正確",
          'Not Logged In': '未登錄',
          "Last Read:": "最後閱讀:",
          "Cache & Restore": "緩存與恢復",
          "Clear Cache Period": "清除緩存周期",
          "Day": "天",
          "Days": "天",
          "Clear Cache": "清除緩存",
          "Are you sure to clear cache?": "您確定要清除緩存嗎？",
          "Restore": "恢復",
          "Cache Cleared": "緩存已清除",
          "General Settings": "常規設置",
          "Initialize App": "初始化應用",
          "Are you sure to initialize app?": "您確定要初始化應用嗎？",
          "App Initialized": "應用已初始化",
          "H24": "24h",
          "D7": "7天",
          "D30": "30天",
          "The purpose of this App is only for learning, communication, and personal interest. Any content displayed comes from the internet and is not related to the developer":
              "本App的開發目的僅為學習交流與個人興趣, 顯示的任何內容均來自網絡, 與開發者無關",
          "If you encounter any problems during use, please first confirm whether it is a problem with your device, and then provide feedback":
              "如果在使用中發現問題, 請先確認是否為自己的設備問題, 然後再進行反饋",
          "The developer is not responsible for whether the problem can be solved":
              "開發者不對能否解決問題負責",
//below are translation with parameters
          "at_page": "第@page/@total頁",
          "block_cate": '屏蔽分類"@cate?"',
          "continue_page": "繼續閱讀:@eps-P@page",
        },
      };
}
